### ISSUE TITLE
Works well with Android tablet

### ISSUE THREAD

**Issue by nilababaei** [jako-ry/animal-rescue-website#3]
Your website works perfectly with Chrome and Opera on an Android tablet! The only thing is that the footer seems to move the text in your list to another line and it looks a bit off.

![img_0272](https://user-images.githubusercontent.com/31959337/49837529-ab7e1280-fd74-11e8-9f82-bd4a78305b90.JPG)

**Comment by jako-ry** [comment]
Thanks a bunch, I totally forgot to test my website on tablets.
