### ISSUE TITLE
Firefox text size increase

### ISSUE THREAD

**Issue by megan-smith-6** [jako-ry/animal-rescue-website#7]
The contact us info goes off the screen when the text size is increased on the smallest size
<img width="321" alt="screen shot 2018-12-11 at 6 48 04 pm" src="https://user-images.githubusercontent.com/31959302/49837689-55f63580-fd75-11e8-9df9-9fe0570477bc.png">
I think you could reduce the size of your gutter because it makes the text width really small when the text size is increased.
<img width="321" alt="screen shot 2018-12-11 at 6 50 49 pm" src="https://user-images.githubusercontent.com/31959302/49837746-b2595500-fd75-11e8-9b57-cbc24d0be25b.png">

**Comment by jako-ry** [comment]
Thanks, I reduced the gutter size and added an invisible break to the email addresses.
